module.exports = {
  'flowtype/boolean-style': ['error', 'boolean'],
  'flowtype/define-flow-type': ['warn'],
  'flowtype/delimiter-dangle': ['error', 'never'],
  'flowtype/generic-spacing': ['error', 'never'],
  'flowtype/no-primitive-constructor-types': ['error'],
  'flowtype/no-types-missing-file-annotation': ['error'],
  'flowtype/no-weak-types': ['error'],
  'flowtype/object-type-delimiter': ['error', 'comma'],
  'flowtype/require-parameter-type': ['error'],
  'flowtype/require-return-type': ['error', 'always', { annotateUndefined: 'never' }],
  'flowtype/require-valid-file-annotation': ['error'],
  'flowtype/semi': ['error', 'always'],
  'flowtype/space-after-type-colon': ['error', 'always'],
  'flowtype/space-before-generic-bracket': ['error', 'never'],
  'flowtype/space-before-type-colon': ['error', 'never'],
  'flowtype/type-id-match': ['error', "^([A-Z][a-z0-9]+)+Type$"],
  'flowtype/union-intersection-spacing': ['error', 'always'],
  'flowtype/use-flow-type': ['warn'],
  'flowtype/valid-syntax': ['warn'],
  'flowtype/newline-after-flow-annotation': ['error', 'verbose'],
  'flowtype/array-style-simple-type': ['warn', 'verbose'],


  'flowtype/no-dupe-keys': [],
  'flowtype/no-existential-type': [],
  'flowtype/no-flow-fix-me-comments': [],
  'flowtype/no-mutable-array': [],
  'flowtype/no-unused-expressions': [],
  'flowtype/require-compound-type-alias': [],
  'flowtype/require-exact-type': [],
  'flowtype/require-types-at-top': [],
  'flowtype/array-style-complex-type': [1, 'verbose'],
  'flowtype/require-variable-type': [],
  'flowtype/sort-keys': [],
  'flowtype/type-import-style': [],
}
