module.exports = {
  'flowtype/boolean-style': [2, 'boolean'],
  'flowtype/define-flow-type': 1,
  'flowtype/delimiter-dangle': [2, 'never'],
  'flowtype/generic-spacing': [2, 'never'],
  'flowtype/no-primitive-constructor-types': 2,
  'flowtype/no-types-missing-file-annotation': 2,
  'flowtype/no-weak-types': 2,
  'flowtype/object-type-delimiter': [2, 'comma'],
  'flowtype/require-parameter-type': 2,
  'flowtype/require-return-type': [2, 'always', { annotateUndefined: 'never' }],
  'flowtype/require-valid-file-annotation': 2,
  'flowtype/semi': [2, 'always'],
  'flowtype/space-after-type-colon': [2, 'always'],
  'flowtype/space-before-generic-bracket': [2, 'never'],
  'flowtype/space-before-type-colon': [2, 'never'],
  'flowtype/type-id-match': [2, '^([A-Z][a-z0-9]+)+Type$'],
  'flowtype/union-intersection-spacing': [2, 'always'],
  'flowtype/use-flow-type': 1,
  'flowtype/valid-syntax': 1,
  'flowtype/newline-after-flow-annotation': [2, 'always'],
  'flowtype/array-style-simple-type': [1, 'verbose'],
  'flowtype/no-dupe-keys': 2,
  'flowtype/no-existential-type': 2,
  'flowtype/no-flow-fix-me-comments': 1,
  'flowtype/no-mutable-array': 1,
  'flowtype/no-unused-expressions': 1,
  'flowtype/require-compound-type-alias': [2, 'always'],
  'flowtype/require-exact-type': [2, 'always'],
  'flowtype/require-types-at-top': [2, 'always'],
  'flowtype/array-style-complex-type': [1, 'verbose'],
  'flowtype/require-variable-type': [2, { excludeVariableMatch: '^_' }],
  'flowtype/sort-keys': [2, 'asc', { caseSensitive: true, natural: true }],
  'flowtype/type-import-style': [2, 'identifier'],
}
