module.exports = {
  'jest/consistent-test-it': [2, { fn: 'it', withinDescribe: 'it' }],
  'jest/expect-expect': 1,
  'jest/lowercase-name': 2,
  'jest/no-alias-methods': 2,
  'jest/no-disabled-tests': 1,
  'jest/no-focused-tests': 2,
  'jest/no-hooks': 2,
  'jest/no-identical-title': 2,
  'jest/no-jasmine-globals': 2,
  'jest/no-jest-import': 1,
  'jest/no-large-snapshots': 2,
  'jest/no-test-callback': 1,
  'jest/no-test-prefixes': 1,
  'jest/no-test-return-statement': 2,
  'jest/prefer-expect-assertions': 1,
  'jest/prefer-spy-on': 1,
  'jest/prefer-strict-equal': 1,
  'jest/prefer-to-be-null': 1,
  'jest/prefer-to-be-undefined': 1,
  'jest/prefer-to-contain': 1,
  'jest/prefer-to-have-length': 1,
  'jest/require-tothrow-message': 2,
  'jest/valid-describe': 2,
  'jest/valid-expect-in-promise': 2,
  'jest/valid-expect': 2
}
