module.exports = {
  'jest/consistent-test-it': [
    'error', {
      fn: 'it',
      withinDescribe: 'it'
    }
  ],
  'jest/expect-expect': 'warn',
  'jest/lowercase-name': 'error',
  'jest/no-alias-methods': 'error',
  'jest/no-commented-out-tests': 'warn',
  'jest/no-conditional-expect': 'warn',
  'jest/no-deprecated-functions': 'warn',
  'jest/no-disabled-tests': 'warn',
  'jest/no-done-callback': 'warn',
  'jest/no-duplicate-hooks': 'warn',
  'jest/no-export': 'warn',
  'jest/no-focused-tests': 'error',
  'jest/no-hooks': 'warn',
  'jest/no-identical-title': 'error',
  'jest/no-if': 'warn',
  'jest/no-interpolation-in-snapshots': 'warn',
  'jest/no-jasmine-globals': 'error',
  'jest/no-jest-import': 'warn',
  'jest/no-large-snapshots': 'error',
  'jest/no-mocks-import': 'warn',
  'jest/no-restricted-matchers': 'warn',
  'jest/no-standalone-expect': 'warn',
  'jest/no-test-prefixes': 'warn',
  'jest/no-test-return-statement': 'error',
  'jest/prefer-called-with': 'warn',
  'jest/prefer-expect-assertions': 'warn',
  'jest/prefer-hooks-on-top': 'warn',
  'jest/prefer-spy-on': 'error',
  'jest/prefer-strict-equal': 'error',
  'jest/prefer-to-be-null': 'error',
  'jest/prefer-to-be-undefined': 'error',
  'jest/prefer-to-contain': 'error',
  'jest/prefer-to-have-length': 'warn',
  'jest/prefer-todo': 'warn',
  'jest/require-to-throw-message': 'warn',
  'jest/require-top-level-describe': 'warn',
  'jest/valid-describe': 'error',
  'jest/valid-expect': 'error',
  'jest/valid-expect-in-promise': 'error',
  'jest/valid-title': 'error'
}
