module.exports = {
  'unicorn/catch-error-name': [2, { name: 'err' }],
  'unicorn/custom-error-definition': 2,
  'unicorn/error-message': 2,
  'unicorn/escape-case': 2,
  'unicorn/explicit-length-check': [2, { 'non-zero': 'not-equal' }],
  'unicorn/filename-case': 0, // This is handled already by eslint-plugin-filenames
  'unicorn/import-index': 2,
  'unicorn/new-for-builtins': 2,
  'unicorn/no-abusive-eslint-disable': 2,
  'unicorn/no-array-instanceof': 2,
  'unicorn/no-console-spaces': 2,
  'unicorn/no-fn-reference-in-iterator': 0,
  'unicorn/no-hex-escape': 2,
  'unicorn/no-keyword-prefix': 0,
  'unicorn/no-new-buffer': 2,
  'unicorn/no-process-exit': 2,
  'unicorn/no-unreadable-array-destructuring': 2,
  'unicorn/no-unsafe-regex': 2,
  'unicorn/no-unused-properties': 1,
  'unicorn/no-zero-fractions': 2,
  'unicorn/number-literal-case': 2,
  'unicorn/prefer-add-event-listener': 2,
  'unicorn/prefer-event-key': 2,
  'unicorn/prefer-exponentiation-operator': 2,
  'unicorn/prefer-flat-map': 2,
  'unicorn/prefer-includes': 2,
  'unicorn/prefer-node-append': 1,
  'unicorn/prefer-node-remove': 1,
  'unicorn/prefer-query-selector': 2,
  'unicorn/prefer-spread': 2,
  'unicorn/prefer-starts-ends-with': 2,
  'unicorn/prefer-text-content': 2,
  'unicorn/prefer-type-error': 2,
  'unicorn/prevent-abbreviations': 2,
  'unicorn/regex-shorthand': 2,
  'unicorn/throw-new-error': 2,
}
