module.exports = {
  'unicorn/catch-error-name': ['error', { name: 'err' }],
  'unicorn/custom-error-definition': 'error',
  'unicorn/error-message': 'error',
  'unicorn/escape-case': 'error',
  'unicorn/explicit-length-check': ['error', { 'non-zero': 'not-equal' }],
  'unicorn/filename-case': 'off', // This is handled already by eslint-plugin-filenames
  'unicorn/import-index': 'error',
  'unicorn/new-for-builtins': 'error',
  'unicorn/no-abusive-eslint-disable': 'error',
  'unicorn/no-array-instanceof': 'error',
  'unicorn/no-fn-reference-in-iterator': 'off',
  'unicorn/no-hex-escape': 'error',
  'unicorn/no-new-buffer': 'error',
  'unicorn/no-process-exit': 'error',
  'unicorn/no-unsafe-regex': 'error',
  'unicorn/number-literal-case': 'error',
  'unicorn/prefer-add-event-listener': 'error',
  'unicorn/prefer-exponentiation-operator': 'error',
  'unicorn/prefer-spread': 'error',
  'unicorn/prefer-starts-ends-with': 'error',
  'unicorn/prefer-type-error': 'error',
  'unicorn/regex-shorthand': 'error',
  'unicorn/throw-new-error': 'error',
  'unicorn/no-console-spaces': 'error',
  'unicorn/no-unreadable-array-destructuring': 'error',
  'unicorn/no-unused-properties': 'warn',
  'unicorn/prefer-node-append': 'warn',
}
