module.exports = {
  'unicorn/catch-error-name': ['error', { name: 'err' }],
  'unicorn/custom-error-definition': 0,
  'unicorn/error-message': 2,
  'unicorn/escape-case': 2,
  'unicorn/explicit-length-check': 2,
  'unicorn/import-index': 2,
  'unicorn/new-for-builtins': 2,
  'unicorn/no-abusive-eslint-disable': 2,
  'unicorn/no-array-instanceof': 2,
  'unicorn/no-fn-reference-in-iterator': 0,
  'unicorn/no-hex-escape': 2,
  'unicorn/no-new-buffer': 2,
  'unicorn/no-process-exit': 2,
  'unicorn/no-unsafe-regex': 2,
  'unicorn/number-literal-case': 2,
  'unicorn/prefer-add-event-listener': 2,
  'unicorn/prefer-exponentiation-operator': 2,
  'unicorn/prefer-spread': 2,
  'unicorn/prefer-starts-ends-with': 2,
  'unicorn/prefer-type-error': 2,
  'unicorn/regex-shorthand': 2,
  'unicorn/throw-new-error': 2
}
